#!/bin/bash
path="/home/username/"
cmddir="${path}Downloads/prog_files"
commands="\
commands.txt \
commands1.txt \
commands2.txt \
commands3.txt \
commands4.txt \
commands5.txt \
"
for cmd in ${commands}
	do \
	cmd_file="${cmddir}/${cmd}"
	./a < ${cmd_file} > res.txt
	../0_database_mm/a ../database_mm/a.txt < ${cmd_file} > ../0_database_mm/res.txt
	cat res.txt | grep '^ *Student' | wc
	cat ../0_database_mm/res.txt | grep '^ *Student' | wc
done
